version: 2

models:
  - name: hcc_ConfigCategoryHCCMap
    data_tests:
      - model_column_capitalized_according_to_config:
          identifier: 'qdw_hcc_ConfigCategoryHCCMap'
          meta:
            requirement: [ 'FDR-1999' ]